name: Pull request build
on:
  pull_request:

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Build
        run: bun run build
        env:
          NEXT_PUBLIC_ENABLED_CHAIN_IDS: x
          NEXT_PUBLIC_IPFS_ENDPOINTS: https://ipfs/
          NEXT_PUBLIC_ETHEREUM_RPC_URL: x
          NEXT_PUBLIC_SEPOLIA_RPC_URL: x
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: x
          NEXT_PUBLIC_WEB3_STORAGE_KEY: x
          NEXT_PUBLIC_ETHERSCAN_API_KEY: x
          NODE_ENV: production
